### ISSUE TITLE
DATA_FINAL is missing

### ISSUE THREAD

**Issue by LouisSerrano** [pswpswpsw/paper-nif#2]
Hi guys, I wanted to check out the KS data to have a look a closer look, but the DATA_FINAL folder which is supposed to contain both datasets is not on the repo. Could you tell me where I could find it or how I could generate the data please ?

Thank you !

**Comment by pswpswpsw** [comment]
@LouisSerrano As I have noted in the readme file, since it will be a terrible idea to put GB data on github repo, you have to download from my google drive. The link is also in the readme file but here you are: [google drive link](https://drive.google.com/drive/folders/1CfMUKBfuo92BN_qIWbNxzfLoxRradFRw?usp=sharing  )

Please go to **sec_3_1_data.zip** to look for what you need, i.e., DATA_FINAL

**Comment by LouisSerrano** [comment]
@pswpswpsw Ok great thank you very much ! Indeed, I forgot to check `sec_3_1_data.zip`, my mistake.
Have a good day.
